import { Open_Sans } from 'next/font/google';
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'], 
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={openSans.className}
      >
        {children}
      </body>
    </html>
  );
}
